# Generated by Django 2.2.7 on 2019-11-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mene', models.CharField(max_length=20)),
                ('bread', models.CharField(max_length=20)),
                ('vegetable', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=20)),
                ('drink', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
