# Generated by Django 2.2.7 on 2019-11-19 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='menu',
            new_name='Subway',
        ),
    ]
