# Generated by Django 2.2.7 on 2019-11-15 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contient',
            new_name='content',
        ),
    ]
